"""Paper registry helpers."""

from weighttraits.paper.figures import (
    VARIANT_DIAGNOSTIC_METRICS,
    load_weighttraits_variants_artifact,
    plot_weighttraits_variants_diagnostics,
)

from weighttraits.paper.results import (
    ELLMTREES_VARIANTS_TABLE_COLUMNS,
    RECOVERY_TABLE_COLUMNS,
    WEIGHTTRAITS_VARIANTS_SCHEMA,
    behavior_holdout_draft_table_rows,
    compare_table_artifacts,
    ellmtrees_variants_table_rows,
    load_ellmtrees_variants_registry,
    load_reference_registry,
    load_recovery_registry,
    load_table_registry,
    load_weighttraits_variants_registry,
    recovery_table_rows,
    run_table_registry_comparisons,
    validate_reference_registry,
    validate_table_registry,
    write_behavior_holdout_table_csv,
    write_behavior_holdout_table_json,
    write_ellmtrees_variants_table_csv,
    write_ellmtrees_variants_table_json,
    write_recovery_table_csv,
    write_recovery_table_json,
    weighttraits_variants_table_rows,
    write_weighttraits_variants_table_csv,
    write_weighttraits_variants_table_json,
)

__all__ = [
    "ELLMTREES_VARIANTS_TABLE_COLUMNS",
    "RECOVERY_TABLE_COLUMNS",
    "VARIANT_DIAGNOSTIC_METRICS",
    "WEIGHTTRAITS_VARIANTS_SCHEMA",
    "behavior_holdout_draft_table_rows",
    "compare_table_artifacts",
    "ellmtrees_variants_table_rows",
    "load_ellmtrees_variants_registry",
    "load_reference_registry",
    "load_recovery_registry",
    "load_table_registry",
    "load_weighttraits_variants_registry",
    "load_weighttraits_variants_artifact",
    "plot_weighttraits_variants_diagnostics",
    "recovery_table_rows",
    "run_table_registry_comparisons",
    "validate_reference_registry",
    "validate_table_registry",
    "write_behavior_holdout_table_csv",
    "write_behavior_holdout_table_json",
    "write_ellmtrees_variants_table_csv",
    "write_ellmtrees_variants_table_json",
    "write_recovery_table_csv",
    "write_recovery_table_json",
    "weighttraits_variants_table_rows",
    "write_weighttraits_variants_table_csv",
    "write_weighttraits_variants_table_json",
]
